name: Node.js CI - Prod

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: prod

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - run: pm2 stop app
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn cache clean
      - run: yarn install
      - run: yarn compile
      - run: pm2 restart app
